In [4]:

with open("answer_key.txt", "r") as answer_file:
    answer_lines = answer_file.readlines()

with open("predict_31Oct_1.txt", "r") as predict_file:
    predict_lines = predict_file.readlines()

if len(answer_lines) != len(predict_lines):
    print("The number of lines in answer_key.txt and predict.txt does not match.")
else:
    correct_predictions = 0
    total_predictions = len(answer_lines)

    for i in range(total_predictions):
        answer_label = answer_lines[i].strip().split("\t")[1]
        predict_label = predict_lines[i].strip().split("\t")[1]

        if answer_label == predict_label:
            correct_predictions += 1

    accuracy = (correct_predictions / total_predictions) * 100
    print(f"Accuracy: {accuracy:.2f}%")


Accuracy: 57.64%


In [2]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import numpy as np


with open("answer_key.txt", "r") as answer_file:
    answer_lines = answer_file.readlines()

with open("predict_31Oct_1.txt", "r") as predict_file:
    predict_lines = predict_file.readlines()

# Extract the true labels and predicted labels
true_labels = [line.strip().split("\t")[1] for line in answer_lines]
predicted_labels = [line.strip().split("\t")[1] for line in predict_lines]


unique_labels = list(set(true_labels + predicted_labels))

confusion = confusion_matrix(true_labels, predicted_labels, labels=unique_labels)
accuracy = accuracy_score(true_labels, predicted_labels)


class_report = classification_report(true_labels, predicted_labels, target_names=unique_labels)

print("Confusion Matrix:")
print(confusion)

print("\nClassification Report:")
print(class_report)

print("Accuracy: {:.2f}%".format(accuracy * 100))



Confusion Matrix:
[[196   0   0  12   0  74   6   0   4   0]
 [  4 131   4  34   0  56   0   1  28   0]
 [  0   1 251  18   1  37   0   2  18   0]
 [ 32   9  14 103  35 178  12  23  45   3]
 [  1   0   0  23 160  46   0   0   2   1]
 [  1   1   1   7   9 283   0   0  10   0]
 [  3   1   0   3   1  64 118   1   1   0]
 [  0   1   1  11   0 100   0 144   4   0]
 [  2   2   2  14   0  45   0   6 160   0]
 [  2   1   4  24   4  53   0   0  48  20]]

Classification Report:
                    precision    recall  f1-score   support

Entity-Destination       0.91      0.77      0.83       328
     Entity-Origin       0.30      0.91      0.45       312
      Cause-Effect       0.87      0.61      0.72       192
             Other       0.81      0.67      0.74       292
 Member-Collection       0.89      0.51      0.65       258
   Component-Whole       0.83      0.13      0.22       156
 Content-Container       0.76      0.69      0.72       233
     Message-Topic       0.81      0.55      0