In [1]:
import re


input_file_path = '/content/drive/MyDrive/Colab Notebooks/results/output_base.txt'


output_file_path = '/content/drive/MyDrive/Colab Notebooks/results/output_base2.txt'

with open(input_file_path, 'r') as input_file, open(output_file_path, 'w') as output_file:

    for line in input_file:

        modified_line = re.sub(r'\(e[12],e[12]\)', '', line)


        output_file.write(modified_line)

In [2]:
with open("/content/drive/MyDrive/Colab Notebooks/data/answer_key.txt", "r") as answer_file:
    answer_lines = answer_file.readlines()

with open("/content/drive/MyDrive/Colab Notebooks/results/output_base2.txt", "r") as predict_file:
    predict_lines = predict_file.readlines()

if len(answer_lines) != len(predict_lines):
    print("The number of lines in answer_key.txt and predict.txt does not match.")
else:
    correct_predictions = 0
    total_predictions = len(answer_lines)

    for i in range(total_predictions):
        answer_label = answer_lines[i].strip().split("\t")[1]
        predict_label = predict_lines[i].strip().split("\t")[1]

        if answer_label == predict_label:
            correct_predictions += 1

    accuracy = (correct_predictions / total_predictions) * 100
    print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 82.92%


In [3]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import numpy as np

with open("/content/drive/MyDrive/Colab Notebooks/data/answer_key.txt", "r") as answer_file:
    answer_lines = answer_file.readlines()

with open("/content/drive/MyDrive/Colab Notebooks/results/output_base2.txt", "r") as predict_file:
    predict_lines = predict_file.readlines()


true_labels = [line.strip().split("\t")[1] for line in answer_lines]
predicted_labels = [line.strip().split("\t")[1] for line in predict_lines]

unique_labels = list(set(true_labels + predicted_labels))

confusion = confusion_matrix(true_labels, predicted_labels, labels=unique_labels)
accuracy = accuracy_score(true_labels, predicted_labels)

class_report = classification_report(true_labels, predicted_labels, target_names=unique_labels)

print("Confusion Matrix:")
print(confusion)

print("\nClassification Report:")
print(class_report)

print("Accuracy: {:.2f}%".format(accuracy * 100))



Confusion Matrix:
[[304   2   1   1   0   0   0   0  20   0]
 [  8 203   1   9   0   0   0   0  36   1]
 [  0   0 242   0   0   1   1   0  17   0]
 [  2   1   1 191   4   0   0   0  32   0]
 [  1   0   0   7 102   0   5   0  39   2]
 [  0   1   0   0   0 210   4   0  17   1]
 [  0   1   4   1   4  12 245   1  44   0]
 [  0   0   0   0   0   0   0 162  24   6]
 [ 14  11  21  14   9  25  19   9 317  15]
 [  0   0   0   0   0   0   1   3  11 277]]

Classification Report:
                    precision    recall  f1-score   support

      Cause-Effect       0.92      0.93      0.93       328
     Entity-Origin       0.89      0.79      0.83       312
     Message-Topic       0.93      0.84      0.88       192
  Product-Producer       0.92      0.95      0.93       292
 Instrument-Agency       0.93      0.79      0.85       258
 Member-Collection       0.86      0.65      0.74       156
   Component-Whole       0.85      0.90      0.87       233
 Content-Container       0.90      0.93      0

In [4]:
import re


input_file_path = '/content/drive/MyDrive/Colab Notebooks/results/output_large.txt'


output_file_path = '/content/drive/MyDrive/Colab Notebooks/results/output_large2.txt'

with open(input_file_path, 'r') as input_file, open(output_file_path, 'w') as output_file:

    for line in input_file:

        modified_line = re.sub(r'\(e[12],e[12]\)', '', line)


        output_file.write(modified_line)

In [5]:
with open("/content/drive/MyDrive/Colab Notebooks/data/answer_key.txt", "r") as answer_file:
    answer_lines = answer_file.readlines()

with open("/content/drive/MyDrive/Colab Notebooks/results/output_large2.txt", "r") as predict_file:
    predict_lines = predict_file.readlines()

if len(answer_lines) != len(predict_lines):
    print("The number of lines in answer_key.txt and predict.txt does not match.")
else:
    correct_predictions = 0
    total_predictions = len(answer_lines)

    for i in range(total_predictions):
        answer_label = answer_lines[i].strip().split("\t")[1]
        predict_label = predict_lines[i].strip().split("\t")[1]

        if answer_label == predict_label:
            correct_predictions += 1

    accuracy = (correct_predictions / total_predictions) * 100
    print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 83.77%


In [6]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import numpy as np

with open("/content/drive/MyDrive/Colab Notebooks/data/answer_key.txt", "r") as answer_file:
    answer_lines = answer_file.readlines()

with open("/content/drive/MyDrive/Colab Notebooks/results/output_large2.txt", "r") as predict_file:
    predict_lines = predict_file.readlines()


true_labels = [line.strip().split("\t")[1] for line in answer_lines]
predicted_labels = [line.strip().split("\t")[1] for line in predict_lines]

unique_labels = list(set(true_labels + predicted_labels))

confusion = confusion_matrix(true_labels, predicted_labels, labels=unique_labels)
accuracy = accuracy_score(true_labels, predicted_labels)

class_report = classification_report(true_labels, predicted_labels, target_names=unique_labels)

print("Confusion Matrix:")
print(confusion)

print("\nClassification Report:")
print(class_report)

print("Accuracy: {:.2f}%".format(accuracy * 100))



Confusion Matrix:
[[310   2   1   2   0   0   0   0  13   0]
 [  6 225   0   5   0   0   2   0  18   2]
 [  0   0 232   0   0   1  11   0  17   0]
 [  3   3   2 195   6   0   1   0  21   0]
 [  1   0   0   6 112   0   4   0  33   0]
 [  0   1   1   0   1 197   9   0  23   1]
 [  0   0   3   2   4   4 276   2  21   0]
 [  0   0   1   0   0   0   7 174   5   5]
 [ 20  13  26  16   9  26  28  14 286  16]
 [  0   0   0   0   0   0   0   4  19 269]]

Classification Report:
                    precision    recall  f1-score   support

      Cause-Effect       0.91      0.95      0.93       328
     Entity-Origin       0.82      0.88      0.85       312
     Message-Topic       0.90      0.91      0.90       192
  Product-Producer       0.92      0.92      0.92       292
 Instrument-Agency       0.92      0.87      0.90       258
 Member-Collection       0.85      0.72      0.78       156
   Component-Whole       0.86      0.85      0.85       233
 Content-Container       0.87      0.89      0